defaults:
    run:
        working-directory: ./server

name: Check code with ESLint and Prettier on server
on:
    pull_request:
    push:
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checks out the latest Git commit
              uses: actions/checkout@v2
            - name: Sets up a Node.js environment
              uses: actions/setup-node@v2
            - run: npm ci
            - run: npx eslint --ext .ts --max-warnings 0 .
    prettier:
        runs-on: ubuntu-latest
        steps:
            - name: Checks out the latest Git commit
              uses: actions/checkout@v2
            - name: Sets up a Node.js environment
              uses: actions/setup-node@v2
            - run: npm ci
            - run: npx prettier --config .prettierrc.js -l "*.{ts,json}"
